spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web

lotto:
  number-generator:
    lotteryRunOccurrence: "59 19 * * 6 ?"
  result-checker:
    transformToResultOccurrence: "* */1 * * * *"
    checkNumbersOccurrence: "1 20 * * 6 ?"
